level: info
interval: 0 # seconds
catnap:
  number: -1
  duration: 2 # minutes
sleep:
  number: -1
  duration: 30 # minutes
#playlist:
#  - 4234112
#  - 4312424
accounts:
  - phone: 18682283321
    passwd: "67873437868573c6cf0c965a5157016d"
    code: 86
    expired: 2022-09-06
    only_sign: false
    unstable: false
